apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: notebook-dev

commonLabels:
  deployment: dev

resources:
- ../../base

patchesJson6902:
- path: all-set-imagepullpolicy-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: notes
- path: all-set-imagepullpolicy-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: notes-app
- path: all-set-imagepullpolicy-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: email
- path: ingress-sethost-patch.yaml
  target:
    group: networking.k8s.io
    version: v1beta1
    kind: Ingress
    name: notebook-ingress