apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: notebook-deployment
deploy:
  kustomize:
    paths:
    - overlays/dev
profiles:
- name: dev
  deploy:
    kustomize:
      paths:
      - overlays/dev
- name: staging
  deploy:
    kustomize:
      paths:
      - overlays/staging
- name: prod
  deploy:
    kustomize:
      paths:
      - overlays/prod

