apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: notebook-deployment
deploy:
  kustomize:
    paths:
    - overlays/dev
profiles:
- name: prod
  deploy:
    kustomize:
      paths:
      - overlays/prod
- name: staging
  deploy:
    kustomize:
      paths:
      - overlays/staging
