apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- notebook-email.yaml

configMapGenerator:
  - name: email-application-properties
    files:
      - application.properties
