apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: notebook-staging

commonLabels:
  deployment: staging

resources:
- ../../base

# lock down staging images
images:
  - name: notebook/note-service
    newTag: staging-head
  - name: notebook/email-service
    newTag: staging-head
  - name: notebook/note-app
    newTag: staging-head
