apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: notebook-prod

nameSuffix: -prod

commonLabels:
  deployment: prod

resources:
  - ../../base

# lock down production images
images:
  - name: notebook/note-service
    newTag: production-head
  - name: notebook/email-service
    newTag: production-head
  - name: notebook/note-app
    newTag: production-head