apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- notebook-service.yaml

configMapGenerator:
  - name: notes-application-properties
    files:
      - application.properties
