apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- notebook-mongo.yaml
- notebook-oauth.yaml
- notebook-service.yaml
- notebook-gateway.yaml

configMapGenerator:
  
  - name: notebook-realm-config
    files:
    - notebook-realm.json
  - name: notes-application-properties
    files:
      - notes-application.properties

