apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notebook-ingress
spec:
  rules:
  - host: notebook.com
    http:
      paths:
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: oauth
            port:
              name: http-web
      - path: /note
        pathType: Prefix
        backend:
          service:
            name: notes
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: notes-app
            port:
              number: 80
